### PR TITLE
Reformat & setSpeed improvements

### PR DESCRIPTION
**Pull request by fanquake**
I’ve reformatted the code for readability. The reformat commit contains no actual code changes.

Rather than define multiple functions to print speeds, keep the raw &
associated speed (in km/hr) in a dictionary, and print it when SetSpeed is called.

### CODE REVIEW

**Comment by fanquake** [comment]
Due to the formatting changes (which will be a one time thing), it'll be easiest to look at this Pull Request either as individual commits, i.e under the `Commits' tab, click on the Replace Seedx() commit to view those changes separate to the others. 

Alternatively you can append ?w=1 to the end of this URL, i.e `https://github.com/mattdreimer/AutonomousGrainCart/pull/5?w=1`
then when you look at the files changed tab, it will show the diff without all of the messy formatting/whitespace change.

**Comment by mattdreimer** [comment]
The first two commits of this pull request look great. Thanks for documenting how to get it working on Mac.  It's only Replace speedX() functions with a dictionary that I have concerns with.  I made a comment in the code hopefully its clear.  I'm not sure if I should be using git cherry pick to merge the formatting commits or wait till we can resolve the Replace speedX() functions with a dictionary issue? I'm very new to all this so I don't want to make a giant boondoggle out of it.  Thanks for helping

**Comment by fanquake** [comment]
@mattdreimer Using cherry pick would be fine. Feel free to grab the working commit here, and merge them. I'm going to do something more comprehensive in regards to setSpeed.

**Comment by mattdreimer** [comment]
I grabbed both commits. And closed this pull request

**Pull request closed without merging**
